---
name: "Release"

on:
  push:
    branches:
      - ci/* 
    tags:
    - '*'

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up OpenSCAD
        uses: pkoehlers/openscad-build-action@v1.0.2
        with:
          input-file: 'holder.scad'
          output-file: 'holder.stl'
          # customizer-parameter-file: 'holder.json'
          # customizer-parameter-set: 'with_something'
      # - name: Install OpenScad
        # run: sudo apt-get install -y openscad
      # - name: "Build & test"
        # run: make zip
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.stl
