---
name: "Release"

on:
  push:
    branches:
      - ci/* 
    tags:
    - '*'

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up OpenSCAD
        uses: pkoehlers/openscad-build-action@v1.0.2

        with:
          input-file: 'holder.scad'
          output-file: 'holder.stl'
          # customizer-parameter-file: 'holder.json'
          # customizer-parameter-set: 'with_something'
      - name: Archive stl artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stl-output
          path: holder.stl
  pre-release:
    if: startsWith(github.ref, 'refs/heads/ci')
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    needs: build
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "latest"
          files: |
            *.stl
          
